import Head from 'next/head';
import Image from 'next/image';

// styles
import styles from '@/src/styles/Home.module.css';


export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.image__container}> 
					<Image
						src='/El sueño del pibe - mural - Andres Iglesias - niño de cobre.webp'
						width={2659}
						height={4097}
						alt='Pared blanca, parte trasera de un edificio de aproximadamente 75 metros de altura, donde se pintará el mural más grande del mundo dedicado al astro del fútbol mundial: Lionel Messi'
						priority
					/>
					<h1 className={styles.title}>...muy pron10</h1>
					<h1 className={styles.subtitle}>...y será gigante</h1>
				</div>
			</main>
		</>
	);
}
